### PR TITLE
`Communication`: Reintroduce foreign key constraints and offline primary keys

### LINKED ISSUE #62: `Communication`: Index constraints cause crashes
Recently a [hotfix](https://github.com/ls1intum/artemis-android/releases/tag/1.0.1) was released that removed some of the foreign key constraints. This was due to the foreign key constraints causing a variety of crashes in the application. However, this means that the data integrity is not maintained properly.

The foreign key and primary key constraints should be reworked in such a way that they:

1. Do not cause any crashes
2. Maintain proper data integrity

### PR DESCRIPTION
**Pull request by PaRangger**
### Motivation

In the hotfix for version [1.0.1](https://github.com/ls1intum/artemis-android/releases/tag/1.0.1) and [1.0.2](https://github.com/ls1intum/artemis-android/releases/tag/1.0.2) the foreign key constraints for reactions were removed. Additionally, the primary key constraints for posts and reactions were altered to include the server_id. These changes were done to prevent the application from crashing. This however introduced the problem that while the app was running without crashes, the data integrity is not given anymore.

### Description

Pull Request #58 fixed an issue with the answer threads not being shown. This issue also seemed to be the origin of the failing primary and foreign key constraints. Therefore I reverted the changes to include the previous FK and PK checks as they were.

Closes #62

### CODE REVIEW

**Review by FelberMartin — APPROVED** [review]
Tested the App and works as expected without any crashes.

Also tested the migration from the 1.0.3 release to this app state, everything works fine 👍

File: feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/entities/MetisPostContextEntity.kt [hunk 1]
```diff
@@ -14,7 +14,7 @@ import androidx.room.Index
  */
 @Entity(
     tableName = "metis_post_context",
-    primaryKeys = ["client_post_id", "course_id", "conversation_id", "type", "server_id"],
```
Comment (TimOrtel) [inline feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/entities/MetisPostContextEntity.kt:17]: Why is the server id here not needed?

File: feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/entities/PostReactionEntity.kt [hunk 2]
```diff
@@ -7,7 +7,20 @@ import androidx.room.Index
 
 @Entity(
     tableName = "reactions",
-    primaryKeys = ["post_id", "emoji", "author_id", "server_id"],
```
Comment (TimOrtel) [inline feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/entities/PostReactionEntity.kt:10]: Why is the server id here not needed?

File: feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/entities/MetisPostContextEntity.kt (hunk 1 above)
Comment (PaRangger) [reply feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/entities/MetisPostContextEntity.kt:17]: Hey, it used to be like this pre hotfix. As far as I know from reading through comments in the code the server_id could be null in an offline-state.

File: feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/entities/PostReactionEntity.kt (hunk 2 above)
Comment (PaRangger) [reply feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/entities/PostReactionEntity.kt:10]: Same as above 👍🏼

**Review by julian-wls — APPROVED** [review]
Just tested it, and everything seems to work fine.

**Review by TimOrtel — CHANGES_REQUESTED** [review]
Please add some unit Tests to verify that the referential integrity works by writing tests that add messages, delete messages, delete conversations etc.

**Review by julian-wls — APPROVED** [review]
Ran MetisDaoTest and tested adding posts, deleting posts and post reactions. Worked as expected, reapprove.
