### PR TITLE
`Bugfix`: Fix reappearing kick user dialog

### LINKED ISSUE #168: [BUG] Removing user dialog reappearing
### Describe the bug
When removing a user from a group, the removal dialog re-appears after the user has be removed.

**To Reproduce**
- Go to group chat that you created (or create a new one)
- Click settings icon on the top right
- Click the remove user icon on a user
- The remove dialog appears
- Click on "Remove user"
- Observe that user gets removed, BUT the remove dialog re-appear asking to remove the same user again

**Expected behavior**
The dialog should not re-appear after a successful removal

### Screenshots
ArtemisRemoveUserDialogLoop

### Additional context
This was discover while testing #167

### PR DESCRIPTION
**Pull request by julian-wls**
### Problem Description

As described in #168 the kick dialog keeps reappearing after confirming to kick a user from a group/channel.

### Changes

This PR fixes this behavior by adding the onDismiss function call to the completion function. This is necessary to clear the userActionData, which otherwise would not be set to null and causing the dialog to reappear after the reload.
Furthermore, this PR changes the dialog for groups to the correct one.
This PR fixes #168.

### Steps for testing

1. Pick a user with moderation rights or create a group
2. Go to the group or channel
3. Navigate to the settings (top right in the chat view)
4. Try removing a member
5. Verify that the dialog does not reappear after clicking on `Remove user`

### CODE REVIEW

File: feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/PerformActionOnUserDialogs.kt [hunk 1]
```diff
@@ -95,10 +96,10 @@ private fun PerformActionOnUserDialogs(
                     onDismissRequest = onDismiss
                 )
 
-                is GroupChat -> KickUserFromChannelDialog(
+                is GroupChat -> KickUserFromGroupDialog (
                     humanReadableName = humanReadableName,
                     username = username,
-                    channelName = conversation.humanReadableTitle,
+                    groupName = conversation.humanReadableTitle,
```
Comment (FelberMartin) [inline feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/PerformActionOnUserDialogs.kt:102]: The `groupName` is not used anymore in the `KickUserFromGroupDialog`. Either remove the parameter or include it in the dialog texts

**Review by FelberMartin — CHANGES_REQUESTED** [review]
Nice, works as described. Just one minor code comment

**Review by FelberMartin — APPROVED** [review]
Lgtm
